export const SET_POST_FILTER = 'SET_POST_FILTER';
export const IMPORT_POSTDATA = 'IMPORT_POSTDATA';
export const SET_POSTCONTEXT = 'SET_POSTCONTEXT';
export const SET_POST_READING = 'SET_POST_READING';